sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: QcJUEeBHQXuQuWgG7qA/MLstzhSSagcYn8f1bVRxBGf7Q2CDcfaKYPtd0wOMbJRX16Id0sPU6TokEj2tp1rSsbCkf6RZJ5TGG3gnd05OBYApJlc3tKIiUFyQ82pmvioXPXKJ/xGltfGm06o4oLXr+VJRuAVF+TM8uhVoLo3ke7lJBvhwhGSKsy6NHwj7ruWnwkNF6UZoBvmoIkfGwDJRR/YGjf8jn/iruJlHqG6WmEMGyX6J6/RklSRJ56bB+OVj8BE+Ay6w6QNlT3054Z0v2V8R44oAkSx2bF8eDlY6efGmecYeIYMDOTAPgELeXZAHx1rBqylc2+FDUzSopvTH9ZkSbiNH3okETuqe0vHIqlaQS5R+KxvFY9Oih36INMeA19kpWig2VXB7pdrbxLYaYqEZ3y/J0EReNJKvudF4MLkSSEsr5jNxjrqthYKycVxfpGtUdhpnwr+wGafDs28CSlUO3t13OqAI7iO0bsUk2/k90DFH4aAM+3WcYxgfZR7nH/vNvTTqXClH4whafZa8Ft9bbROwKlI4ackmSFUx8d8eId9yPNR2EjsRUKrEPpRORA8CwgMNHc/KEXQiMpbFeW7Ht2dVyXvHt7UI9XE59AQ8J+cOST3OS9h3ZR3P/d2OUEbjXT2qx39M4ZmMnan9nVcLu3fbTduzqD/8BaPwr9A=
    - secure: ZFpGS/e2AVR13Ny282mvdqLEazLff4PY7svue7K0FXoIyPYaLYf1/h2Isxf1NLjgbTaKw6PUWruMq8PlLZYQ/J+lYD5nxfGArLh5mV8/GrYqKuz8QskU1oFSHHm22lO5AzraQNsz5j3AHE314iladey7S/QNjavAqsj0b+P8xJM5waDok9JzQRUCbF8BuAdeXgf3ayZ8kAB9REMn3XPWpUMKB7R7wIkkBF3HyzZbx0bII4EPN0QForbd6595wx5HMsBE25sN0LmA1fsRo6RgjIzfGjlXXpUiYdkorquxbXj2s4Jr3enXXFlQmzPkrPr+nabgCCEhXIcdvJ0K4X1eL5J0ZdkpjT+EOS9OKiQ2QxZJ+ePwSiFQ+Kr6TXMjPT71shYL3yqmQYbLWAFpgTudIKnjLt8THZO6kctHfmvRxXfv/yUxEYTW9soeTHz1BYlvK0VrMIgi36GKa64pKloudJL5DXVnSnxOmQGNkrkSqTcKwf1WBaSjOmiD9bJDdUh54TC94j+xEJ9gznnRCRAVgX0A6WnROGMbCkcP+VuBVcJyCuxMLRF3GhslPHozyOCIO98j+9DoyoJreaqmnI5XBaV1mBvDvZ0/rXNj/N9PBKFbXBX1oX6vtwhM4AiEW2hXyezAy4p8x4WcYDtrmsC13dQ09d2BD/w9803egjzB9GY=
